---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
starbucks_drinkMenu_expanded <- read.csv("data/starbucks_drinkMenu_expanded.csv")
```

```{r}
dim(starbucks_drinkMenu_expanded)
```

```{r}
nrow(starbucks_drinkMenu_expanded)
```

```{r}
ncol(starbucks_drinkMenu_expanded)
```

```{r}
names(starbucks_drinkMenu_expanded)
```

```{r}
glimpse(starbucks_drinkMenu_expanded)
```

```{r}
calorie_count <- select(starbucks_drinkMenu_expanded, Beverage_category, Beverage, Beverage_prep, Calories) 
  
 
calorie_count
```


```{r}
calorie_difference <- mutate(calorie_count, calorie_diff = Calories - 135)
calorie_difference
```

```{r}
calorie_stats <- (calorie_count) %>%
  group_by(Beverage_category)

calorie_stats
```

```{r}
summarise(calorie_stats, mean(Calories))
```

```{r}
summarise(calorie_stats, median(Calories))
```
```{r}
top_calories <- (calorie_stats) %>%
  arrange(desc(Calories)) %>%
  head(3)
top_calories
```

```{r}
least_calories <- (calorie_stats) %>%
  arrange(desc(Calories)) %>%
  tail(3)
least_calories
```

```{r}
beverage_prep_cat <- (calorie_count) %>%
  group_by(Beverage_prep) %>%
  select( Beverage_prep, Calories)
beverage_prep_cat
```
```{r}
mean_bev_prep <- summarise(beverage_prep_cat, mean(Calories))
```

```{r}
mean_all_drinks <- summarise(calorie_count, mean(Calories)) %>%
  pull()
mean_all_drinks
```

```{r}
beverage_brew_above_average <- (beverage_prep_cat) %>%
  filter(Calories > mean_all_drinks)
beverage_brew_above_average
```

