---
title: "Day3 Homework"
output: html_notebook
---

```{r}
library(tidyverse)
```


#Q1

```{r}
movies <- read_csv("data/movies.csv")
```


```{r}
glimpse(movies)
```

# budget is unreadable so would like to see if that could be changed to a more readable format
# original_title and title look similar so could check how many are not identical
# check how many NAs appear in the data
# date is foramtted as characters. check if this is because of missing values


Q2

```{r}
movies_selected <- select(movies, title, budget, runtime )
```

Q3
```{r}
movies_selected %>%
  filter(is.na(title))

```

```{r}
movies_selected %>%
  filter(is.na(budget)) %>%
  nrow()

```
```{r}
movies_selected %>%
  filter(is.na(runtime))

``` 

# answer added after chatting with Lee

```{r}
movies_selected %>%
  summarise(
    count_title_na = sum(is.na(title)),
    count_runtime_na = sum(is.na(runtime)),
    count_budget_na = sum(is.na(budget))
  )
```


Q4

```{r}
movies_runtime <- movies_selected %>%
  mutate(runtime = na_if(runtime, 0))

movies_runtime
```

```{r}
movies_runtime %>%
  summarise(count_runtime_na = sum(is.na(runtime)))


```


Q5

```{r}
movies_imputed <- movies_runtime %>%
  mutate(
    runtime = coalesce(runtime, 
                       median(runtime, na.rm = TRUE)
                       )
  )
movies_imputed
```

```{r}
movies_imputed %>%
  filter(is.na(runtime))%>%
  nrow()
```

Q6

```{r}
movies_imputed %>%
  slice_min(runtime, n = 10)
```

```{r}
movies_imputed %>%
  slice_max(runtime, n = 10)
```

Q7

```{r}
movies_imputed <- movies_imputed %>%
  mutate(
    budget = if_else(budget <100, median(budget), budget)
  )
movies_imputed
```

```{r}
movies %>%
  summarise(
    missing_values_character = sum(is.na(across(where(is.character)))),
    missing_values_numeric = sum(is.na(across(where(is.numeric))))
  )
```

